services:
  smartzone_exporter:
    build: .
    image: smartzone_exporter
    ports:
      - 9345:9345
    environment:
      - TZ=America/Sao_Paulo
      - VSZ_TARGET=${VSZ_TARGET}
      - API_USER=${API_USER}
      - API_PASSWORD=${API_PASSWORD}
      - WLAN_DETAILS=${WLAN_DETAILS}
      - EXTRA_PARAM=--insecure
