services:
  smartzone_exporter:
    build: .
    image: smartzone_exporter
    environment:
      - TZ=America/Sao_Paulo
      - VSZ_TARGET=${VSZ_TARGET}
      - API_USER=${API_USER}
      - API_PASSWORD=${API_PASSWORD}
      - EXTRA_PARAM=--insecure
